import {
    createCard as createCardRepository,
    deleteCard as deleteCardRepository,
    getCard as getCardRepository,
    listCards as listCardsRepository,
    updateCard as updateCardRepository
    
} from "../services/cardService";
import { Response, Request } from "express";
import { Model } from "sequelize";

class CardController {
    
    /**
    * @description Get a specific card of a deck.
    * @param {string} cardId - req.params (string) the card id;
    * @returns A card object with status code.
    */
    async getCard (req: Request, res: Response): Promise<Response<Model>> {
        try {
            const { cardId: id } = req.params;

            const card = await getCardRepository(id);

            return res.status(200).send(card);
        } catch (error) {
            if(error instanceof Error ) return res.status(400).send({message: error.message});

            return res.status(400).send({message: error});
        }
    }

    /**
    * @description List all cards of a  specific deck.
    * @param {string} deckId - req.params (string) the deck id;
    * @returns A list of card objects with status code.
    */
    async listCards (req: Request, res: Response): Promise<Response<Model[]>> {
        try {
            const { deckId: id } = req.params;

            const cards = await listCardsRepository(id);

            return res.status(200).send(cards);
        } catch (error) {
            if(error instanceof Error ) return res.status(400).send({message: error.message});

            return res.status(400).send({message: error});
        }
    }

        /**
    * @description Uptade a deck's card.
    * @param {string} deckId - req.params (string) the deck id;
    * @param {string} cardName - req.body (string) the card name;
    * @param {string} cardContent - req.body (string) the card content;
    * @returns A message with status code.
    */
    async updateCard (req: Request, res: Response): Promise<Response> {
        try {
            const { deckId: id } = req.params;
            const { cardName: name, cardContent: content } = req.body;

            await updateCardRepository(id, name, content);

            return res.status(200).send({message: "Card updated"});
        } catch (error) {
            if(error instanceof Error ) return res.status(400).send({message: error.message});

            return res.status(400).send({message: error});
        }
    }

    /**
    * @description Create a deck's card.
    * @param {string} deckId - req.params (string) the deck id;
    * @param {string} cardName - req.body (string) the card name;
    * @param {string} cardContent - req.body (string) the card content;
    * @param {boolean} isGpt - req.body (boolean) if true, the card content will be generated by Chatgpt and the user content will be ignored;
    * @returns A message with status code.
    */
    async createCard (req: Request, res: Response): Promise<Response> {
        try {
            const { deckId: id } = req.params;
            const { cardName, cardContent, isGpt } = req.body;

            await createCardRepository(id, cardName, cardContent, isGpt); 

            return res.status(200).send({message: "Card created !"});
        } catch (error) {
            if (error instanceof Error) return res.status(400).send({messege: error.message});

            return res.status(400).send({message: error});
            
        }
    }

    /**
    * @description Delete a deck's card.
    * @param {string} cardId - req.params (string) the card id;
    * @returns A message with status code.
    */
    async deleteCard (req: Request, res: Response): Promise<Response> {
        try {
            const { cardId: id } = req.params;

            await deleteCardRepository(id);

            return res.status(200).send({message: "Card deleted !"})
        } catch (error) {
            if (error instanceof Error) return res.status(400).send({message: error.message});
            
            return res.status(400).send({message: error});
        }
    }
}

export default new CardController;